services:
  - type: web
    name: storage-app
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: storage-db
          property: connectionString
